Cahllagerfeld/introduce tailwind
zenml-io/zenml-dashboard pull request #463
Opened 2023-08-24 10:11 UTC by Cahllagerfeld

2023-09-07 12:16 UTC, swapnilhpatil requested changes
Reviewed all changes as it look good and updated few comments. If anyone can more review comments and findings. Please fill free to do so. Thanks.

2023-09-07 12:16 UTC, swapnilhpatil commented on src/ui/layouts/common/layouts/AuthenticatedLayout/AuthenticatedSidebar/Menu/MenuItem.tsx
> +import styles from './MenuItem.module.css';
Just suggestion,
If styles import will be at last below all imports arranged properly. Then, It will be easier to find sometimes imports.

2023-09-07 12:16 UTC, swapnilhpatil commented on src/ui/layouts/common/layouts/AuthenticatedLayout/AuthenticatedSidebar/SideFooter/index.tsx
> +        to="https://github.com/zenml-io/zenml-dashboard/issues/new/choose"
Just suggestion,
It's look like const URL route. If we can move URL like these Inside const URL routes file. IT will be easier to maintain.

2023-12-08 07:03 UTC, Cahllagerfeld commented
closing this for now

2023-12-08 07:03 UTC, closed without merging